### ISSUE TITLE
ModuleDefinition support 

### ISSUE THREAD

**Issue by skyne98** [mono/TsToCSharp#4]
Hey! Trying to compile pixi and phaser definitions I stumbled upon unimplemented ModuleDefinition.

Any plans to support it soon? Any help needed?

**Comment by kjpou1** [comment]
Hello

Have been away on other priorities but can look into it.  All help is greatly needed and appreciated just let me know what you would like to do and ask questions here.

Have not looked at `ModuleDefinition` but we can look at it together if you would like.  That way we can improve the generator and target the specifics that you would like.

Thank you for the interest in the project.

**Comment by liquidboy** [comment]
Just to add more detail to this issue ... 

The offending line in the pixi.js.d.ts is below

`declare module 'pixi.js' {
    export = PIXI;
}`

error from TsToCSharp:

> Error: Unknown statement kind 'ModuleDeclaration'
    at visitStatement (E:\Source\Github\mono\TsToCSharp\dist\TsToCSharpGenerator.js:41:19)
    at node.getStatements.forEach.statement (E:\Source\Github\mono\TsToCSharp\dist\TsToCSharpGenerator.js:29:59)
    at Array.forEach (<anonymous>)
    at visitStatements (E:\Source\Github\mono\TsToCSharp\dist\TsToCSharpGenerator.js:29:26)
    at Object.TsToCSharpGenerator (E:\Source\Github\mono\TsToCSharp\dist\TsToCSharpGenerator.js:14:5)
    at sfs.forEach.astSourceFile (E:\Source\Github\mono\TsToCSharp\dist\TStoCSharp.js:38:60)
    at Array.forEach (<anonymous>)
    at genOptions.fileList.forEach.fileName (E:\Source\Github\mono\TsToCSharp\dist\TStoCSharp.js:37:21)
    at Array.forEach (<anonymous>)
    at Function.main (E:\Source\Github\mono\TsToCSharp\dist\TStoCSharp.js:31:33)
